// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SocialFlowers struct {
	Twitter              int32    `protobuf:"varint,1,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Youtube              int32    `protobuf:"varint,2,opt,name=youtube,proto3" json:"youtube,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialFlowers) Reset()         { *m = SocialFlowers{} }
func (m *SocialFlowers) String() string { return proto.CompactTextString(m) }
func (*SocialFlowers) ProtoMessage()    {}
func (*SocialFlowers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *SocialFlowers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialFlowers.Unmarshal(m, b)
}
func (m *SocialFlowers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialFlowers.Marshal(b, m, deterministic)
}
func (m *SocialFlowers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialFlowers.Merge(m, src)
}
func (m *SocialFlowers) XXX_Size() int {
	return xxx_messageInfo_SocialFlowers.Size(m)
}
func (m *SocialFlowers) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialFlowers.DiscardUnknown(m)
}

var xxx_messageInfo_SocialFlowers proto.InternalMessageInfo

func (m *SocialFlowers) GetTwitter() int32 {
	if m != nil {
		return m.Twitter
	}
	return 0
}

func (m *SocialFlowers) GetYoutube() int32 {
	if m != nil {
		return m.Youtube
	}
	return 0
}

type Person struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32          `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	SFlowers             *SocialFlowers `protobuf:"bytes,3,opt,name=sFlowers,proto3" json:"sFlowers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSFlowers() *SocialFlowers {
	if m != nil {
		return m.SFlowers
	}
	return nil
}

func init() {
	proto.RegisterType((*SocialFlowers)(nil), "main.SocialFlowers")
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x72,
	0xe6, 0xe2, 0x0d, 0xce, 0x4f, 0xce, 0x4c, 0xcc, 0x71, 0xcb, 0xc9, 0x2f, 0x4f, 0x2d, 0x2a, 0x16,
	0x92, 0xe0, 0x62, 0x2f, 0x29, 0xcf, 0x2c, 0x29, 0x49, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0d, 0x82, 0x71, 0x41, 0x32, 0x95, 0xf9, 0xa5, 0x25, 0xa5, 0x49, 0xa9, 0x12, 0x4c, 0x10, 0x19,
	0x28, 0x57, 0x29, 0x9e, 0x8b, 0x2d, 0x00, 0x6c, 0xb4, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e,
	0x2a, 0x58, 0x2b, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x98, 0x0e, 0xd3, 0x03, 0x62,
	0x0a, 0xe9, 0x73, 0x71, 0x14, 0x43, 0xed, 0x93, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd6,
	0x03, 0xb9, 0x46, 0x0f, 0xc5, 0x29, 0x41, 0x70, 0x45, 0x49, 0x6c, 0x60, 0x27, 0x1b, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xca, 0xd7, 0xdd, 0x06, 0xc2, 0x00, 0x00, 0x00,
}
